### ISSUE TITLE
Request code (in README) not working without the right syntax

### ISSUE THREAD

**Issue by ghost** [popphp/pop-http#1]
I've followed the README in this repo, and couldn't get passed the errors if I didn't switched from this:

`$request = new Pop\Http\Server\Request();`

to this:

`$request = new \Pop\Http\Server\Request();`

or this:

```
use Pop\Http;
$request = new Http\Server\Request();
```

**Comment by nicksagona** [comment]
The sample code does work correctly. As it is sample code, it's implied to be at the top level of the namespace declaration. If anyone were to use that code, I would expect them to pay attention to where in their application they dropped it and adjust any namespace declarations according. For example, if a dev dropped it in a top level script file for a quick test, no adjustment would be needed and the example script works just fine. If a dev dropped it inside your application under the namespace declaration of `MyApp\Controller`, I would except that dev to make the proper adjustments to the namespace call within those 2 lines of sample code.
